post_install() {
        /usr/bin/glib-compile-schemas /usr/share/glib-2.0/schemas/
	update-desktop-database -q
	gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
	update-mime-database usr/share/mime
}

pre_upgrade() {
	pre_remove
}

post_upgrade() {
	post_install
}

pre_remove() {
        /usr/bin/glib-compile-schemas /usr/share/glib-2.0/schemas/
}

post_remove() {
	update-desktop-database -q
	gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
	update-mime-database usr/share/mime
}
